// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// grid_worker_rcpp
List grid_worker_rcpp(NumericVector x_llc, NumericVector y_llc, double cellsize, int epsg, std::string size_lbl, double divider, std::string axis_order, std::string id_format, bool generate_ids);
RcppExport SEXP _gridmaker_grid_worker_rcpp(SEXP x_llcSEXP, SEXP y_llcSEXP, SEXP cellsizeSEXP, SEXP epsgSEXP, SEXP size_lblSEXP, SEXP dividerSEXP, SEXP axis_orderSEXP, SEXP id_formatSEXP, SEXP generate_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_llc(x_llcSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_llc(y_llcSEXP);
    Rcpp::traits::input_parameter< double >::type cellsize(cellsizeSEXP);
    Rcpp::traits::input_parameter< int >::type epsg(epsgSEXP);
    Rcpp::traits::input_parameter< std::string >::type size_lbl(size_lblSEXP);
    Rcpp::traits::input_parameter< double >::type divider(dividerSEXP);
    Rcpp::traits::input_parameter< std::string >::type axis_order(axis_orderSEXP);
    Rcpp::traits::input_parameter< std::string >::type id_format(id_formatSEXP);
    Rcpp::traits::input_parameter< bool >::type generate_ids(generate_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_worker_rcpp(x_llc, y_llc, cellsize, epsg, size_lbl, divider, axis_order, id_format, generate_ids));
    return rcpp_result_gen;
END_RCPP
}
// generate_ids_rcpp
List generate_ids_rcpp(NumericVector x_llc, NumericVector y_llc, double cellsize, int epsg, std::string size_lbl, double divider, std::string axis_order, std::string id_format);
RcppExport SEXP _gridmaker_generate_ids_rcpp(SEXP x_llcSEXP, SEXP y_llcSEXP, SEXP cellsizeSEXP, SEXP epsgSEXP, SEXP size_lblSEXP, SEXP dividerSEXP, SEXP axis_orderSEXP, SEXP id_formatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_llc(x_llcSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_llc(y_llcSEXP);
    Rcpp::traits::input_parameter< double >::type cellsize(cellsizeSEXP);
    Rcpp::traits::input_parameter< int >::type epsg(epsgSEXP);
    Rcpp::traits::input_parameter< std::string >::type size_lbl(size_lblSEXP);
    Rcpp::traits::input_parameter< double >::type divider(dividerSEXP);
    Rcpp::traits::input_parameter< std::string >::type axis_order(axis_orderSEXP);
    Rcpp::traits::input_parameter< std::string >::type id_format(id_formatSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_ids_rcpp(x_llc, y_llc, cellsize, epsg, size_lbl, divider, axis_order, id_format));
    return rcpp_result_gen;
END_RCPP
}
// parse_inspire_ids_rcpp
DataFrame parse_inspire_ids_rcpp(CharacterVector inspire, LogicalVector is_long, LogicalVector is_short);
RcppExport SEXP _gridmaker_parse_inspire_ids_rcpp(SEXP inspireSEXP, SEXP is_longSEXP, SEXP is_shortSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type inspire(inspireSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_long(is_longSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_short(is_shortSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_inspire_ids_rcpp(inspire, is_long, is_short));
    return rcpp_result_gen;
END_RCPP
}
// convert_inspire_ids_rcpp
CharacterVector convert_inspire_ids_rcpp(CharacterVector ids, int crs, std::string axis_order);
RcppExport SEXP _gridmaker_convert_inspire_ids_rcpp(SEXP idsSEXP, SEXP crsSEXP, SEXP axis_orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< int >::type crs(crsSEXP);
    Rcpp::traits::input_parameter< std::string >::type axis_order(axis_orderSEXP);
    rcpp_result_gen = Rcpp::wrap(convert_inspire_ids_rcpp(ids, crs, axis_order));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gridmaker_grid_worker_rcpp", (DL_FUNC) &_gridmaker_grid_worker_rcpp, 9},
    {"_gridmaker_generate_ids_rcpp", (DL_FUNC) &_gridmaker_generate_ids_rcpp, 8},
    {"_gridmaker_parse_inspire_ids_rcpp", (DL_FUNC) &_gridmaker_parse_inspire_ids_rcpp, 3},
    {"_gridmaker_convert_inspire_ids_rcpp", (DL_FUNC) &_gridmaker_convert_inspire_ids_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gridmaker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
