# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate Grid Polygons and IDs (C++ Kernel)
#'
#' Creates the geometry (sfc compatible list of matrices) and
#' INSPIRE IDs in a single pass for maximum efficiency.
#'
#' @param x_llc Numeric vector of X coordinates (bottom-left)
#' @param y_llc Numeric vector of Y coordinates (bottom-left)
#' @param cellsize Grid resolution in meters
#' @param epsg EPSG code (e.g. 3035)
#' @param size_lbl Label for short ID (e.g. "1km" or "100m")
#' @param divider Divisor for short ID coordinates
#' @param axis_order "NE" or "EN"
#' @param id_format "both", "long", "short", "none"
#'
#' @return List containing geometry and IDs
#' @export
grid_worker_rcpp <- function(x_llc, y_llc, cellsize, epsg, size_lbl, divider, axis_order, id_format, generate_ids = TRUE) {
    .Call(`_gridmaker_grid_worker_rcpp`, x_llc, y_llc, cellsize, epsg, size_lbl, divider, axis_order, id_format, generate_ids)
}

#' Generate INSPIRE IDs Only (C++ Kernel)
#'
#' Efficiently generates INSPIRE IDs for a set of coordinates.
#'
#' @param x_llc Numeric vector of X coordinates (bottom-left)
#' @param y_llc Numeric vector of Y coordinates (bottom-left)
#' @param cellsize Grid resolution in meters
#' @param epsg EPSG code
#' @param size_lbl Label for short ID
#' @param divider Divisor for short ID coordinates
#' @param axis_order "NE" or "EN"
#' @param id_format "both", "long", "short"
#'
#' @return List containing IDs
#' @export
generate_ids_rcpp <- function(x_llc, y_llc, cellsize, epsg, size_lbl, divider, axis_order, id_format) {
    .Call(`_gridmaker_generate_ids_rcpp`, x_llc, y_llc, cellsize, epsg, size_lbl, divider, axis_order, id_format)
}

#' Parse INSPIRE IDs to Coordinates (C++ Kernel)
#'
#' @param inspire Character vector of IDs
#' @param is_long Logical indicator for long IDs
#' @param is_short Logical indicator for short IDs
#' @return DataFrame with columns: crs, cellsize, x, y
#' @export
parse_inspire_ids_rcpp <- function(inspire, is_long, is_short) {
    .Call(`_gridmaker_parse_inspire_ids_rcpp`, inspire, is_long, is_short)
}

